package com.frotly.yycg.business.analyze.entity;

// Generated 2015-12-24 16:36:49 by Hibernate Tools 4.0.0

import java.util.Date;

import com.frotly.yycg.business.cgd.entity.Yycgd;
import com.frotly.yycg.business.system.entity.Dictinfo;
import com.frotly.yycg.business.system.entity.Usergys;
import com.frotly.yycg.business.system.entity.Useryy;
import com.frotly.yycg.business.ypml.entity.Ypxx;

/**
 * Yybusiness generated by hbm2java
 */
public class Yybusiness implements java.io.Serializable {

	private String id;
	private Useryy useryy;
	private Ypxx ypxx;
	private Usergys usergys;
	private Dictinfo dictinfo;
	private Yycgd yycgd;
	private Float zbjg;
	private Float jyjg;
	private Integer cgl;
	private Float cgje;
	private Integer rkl;
	private Float rkje;
	private String rkdh;
	private String ypph;
	private Float ypyxq;
	private Date rktime;
	private Date fhtime;
	private String yythdid;
	private Integer thl;
	private Float thje;
	private String thzt;
	private String thyy;
	private String yyjsdid;
	private Integer jsl;
	private Float jsje;
	private String jszt;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private Date tjtime;

	public Yybusiness() {
	}

	public Yybusiness(String id, Useryy useryy, Ypxx ypxx, Usergys usergys,
			Dictinfo dictinfo, Yycgd yycgd, Float zbjg, Float jyjg,
			Integer cgl, Float cgje, Date tjtime) {
		this.id = id;
		this.useryy = useryy;
		this.ypxx = ypxx;
		this.usergys = usergys;
		this.dictinfo = dictinfo;
		this.yycgd = yycgd;
		this.zbjg = zbjg;
		this.jyjg = jyjg;
		this.cgl = cgl;
		this.cgje = cgje;
		this.tjtime = tjtime;
	}

	public Yybusiness(String id, Useryy useryy, Ypxx ypxx, Usergys usergys,
			Dictinfo dictinfo, Yycgd yycgd, Float zbjg, Float jyjg,
			Integer cgl, Float cgje, Integer rkl, Float rkje, String rkdh,
			String ypph, Float ypyxq, Date rktime, Date fhtime, String yythdid,
			Integer thl, Float thje, String thzt, String thyy, String yyjsdid,
			Integer jsl, Float jsje, String jszt, String vchar1, String vchar2,
			String vchar3, Date tjtime) {
		this.id = id;
		this.useryy = useryy;
		this.ypxx = ypxx;
		this.usergys = usergys;
		this.dictinfo = dictinfo;
		this.yycgd = yycgd;
		this.zbjg = zbjg;
		this.jyjg = jyjg;
		this.cgl = cgl;
		this.cgje = cgje;
		this.rkl = rkl;
		this.rkje = rkje;
		this.rkdh = rkdh;
		this.ypph = ypph;
		this.ypyxq = ypyxq;
		this.rktime = rktime;
		this.fhtime = fhtime;
		this.yythdid = yythdid;
		this.thl = thl;
		this.thje = thje;
		this.thzt = thzt;
		this.thyy = thyy;
		this.yyjsdid = yyjsdid;
		this.jsl = jsl;
		this.jsje = jsje;
		this.jszt = jszt;
		this.vchar1 = vchar1;
		this.vchar2 = vchar2;
		this.vchar3 = vchar3;
		this.tjtime = tjtime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Useryy getUseryy() {
		return this.useryy;
	}

	public void setUseryy(Useryy useryy) {
		this.useryy = useryy;
	}

	public Ypxx getYpxx() {
		return this.ypxx;
	}

	public void setYpxx(Ypxx ypxx) {
		this.ypxx = ypxx;
	}

	public Usergys getUsergys() {
		return this.usergys;
	}

	public void setUsergys(Usergys usergys) {
		this.usergys = usergys;
	}

	public Dictinfo getDictinfo() {
		return this.dictinfo;
	}

	public void setDictinfo(Dictinfo dictinfo) {
		this.dictinfo = dictinfo;
	}

	public Yycgd getYycgd() {
		return this.yycgd;
	}

	public void setYycgd(Yycgd yycgd) {
		this.yycgd = yycgd;
	}

	public Float getZbjg() {
		return this.zbjg;
	}

	public void setZbjg(Float zbjg) {
		this.zbjg = zbjg;
	}

	public Float getJyjg() {
		return this.jyjg;
	}

	public void setJyjg(Float jyjg) {
		this.jyjg = jyjg;
	}

	public Integer getCgl() {
		return this.cgl;
	}

	public void setCgl(Integer cgl) {
		this.cgl = cgl;
	}

	public Float getCgje() {
		return this.cgje;
	}

	public void setCgje(Float cgje) {
		this.cgje = cgje;
	}

	public Integer getRkl() {
		return this.rkl;
	}

	public void setRkl(Integer rkl) {
		this.rkl = rkl;
	}

	public Float getRkje() {
		return this.rkje;
	}

	public void setRkje(Float rkje) {
		this.rkje = rkje;
	}

	public String getRkdh() {
		return this.rkdh;
	}

	public void setRkdh(String rkdh) {
		this.rkdh = rkdh;
	}

	public String getYpph() {
		return this.ypph;
	}

	public void setYpph(String ypph) {
		this.ypph = ypph;
	}

	public Float getYpyxq() {
		return this.ypyxq;
	}

	public void setYpyxq(Float ypyxq) {
		this.ypyxq = ypyxq;
	}

	public Date getRktime() {
		return this.rktime;
	}

	public void setRktime(Date rktime) {
		this.rktime = rktime;
	}

	public Date getFhtime() {
		return this.fhtime;
	}

	public void setFhtime(Date fhtime) {
		this.fhtime = fhtime;
	}

	public String getYythdid() {
		return this.yythdid;
	}

	public void setYythdid(String yythdid) {
		this.yythdid = yythdid;
	}

	public Integer getThl() {
		return this.thl;
	}

	public void setThl(Integer thl) {
		this.thl = thl;
	}

	public Float getThje() {
		return this.thje;
	}

	public void setThje(Float thje) {
		this.thje = thje;
	}

	public String getThzt() {
		return this.thzt;
	}

	public void setThzt(String thzt) {
		this.thzt = thzt;
	}

	public String getThyy() {
		return this.thyy;
	}

	public void setThyy(String thyy) {
		this.thyy = thyy;
	}

	public String getYyjsdid() {
		return this.yyjsdid;
	}

	public void setYyjsdid(String yyjsdid) {
		this.yyjsdid = yyjsdid;
	}

	public Integer getJsl() {
		return this.jsl;
	}

	public void setJsl(Integer jsl) {
		this.jsl = jsl;
	}

	public Float getJsje() {
		return this.jsje;
	}

	public void setJsje(Float jsje) {
		this.jsje = jsje;
	}

	public String getJszt() {
		return this.jszt;
	}

	public void setJszt(String jszt) {
		this.jszt = jszt;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	public Date getTjtime() {
		return this.tjtime;
	}

	public void setTjtime(Date tjtime) {
		this.tjtime = tjtime;
	}

}
