package com.frotly.yycg.business.system.entity;

// Generated 2015-12-4 21:43:10 by Hibernate Tools 4.0.0

/**
 * Dicttype generated by hbm2java
 */
public class Dicttype implements java.io.Serializable {

	private String typecode;
	private String typename;
	private String remark;
	private Integer typesort;
	private String codelength;

	public Dicttype() {
	}

	public Dicttype(String typecode, String typename) {
		this.typecode = typecode;
		this.typename = typename;
	}

	public Dicttype(String typecode, String typename, String remark,
			Integer typesort, String codelength) {
		this.typecode = typecode;
		this.typename = typename;
		this.remark = remark;
		this.typesort = typesort;
		this.codelength = codelength;
	}

	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getTypesort() {
		return this.typesort;
	}

	public void setTypesort(Integer typesort) {
		this.typesort = typesort;
	}

	public String getCodelength() {
		return this.codelength;
	}

	public void setCodelength(String codelength) {
		this.codelength = codelength;
	}

}
