package com.frotly.yycg.business.system.entity;

// Generated 2015-12-5 12:33:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysPermission generated by hbm2java
 */
public class SysPermission implements java.io.Serializable {

	private String id;
	private String name;
	private String parentid;
	private String url;
	private String icon;
	private String showorder;
	private String isused;
	private String ismenu;
	private String vchar2;
	private String vchar1;
	private String plevel;
//	private Set sysRoles = new HashSet(0);

	
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getShoworder() {
		return this.showorder;
	}

	public void setShoworder(String showorder) {
		this.showorder = showorder;
	}

	public String getIsused() {
		return this.isused;
	}

	public void setIsused(String isused) {
		this.isused = isused;
	}

	public String getIsmenu() {
		return this.ismenu;
	}

	public void setIsmenu(String ismenu) {
		this.ismenu = ismenu;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getPlevel() {
		return this.plevel;
	}

	public void setPlevel(String plevel) {
		this.plevel = plevel;
	}


}
