package com.frotly.yycg.business.system.entity;

// Generated 2015-12-4 21:43:10 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {

	private String id;
	private Userjd userjd;
	private Useryy useryy;
	private Usergys usergys;
	private Dictinfo dictinfoByGroupid;
	private Dictinfo dictinfoByUserstate;
	private String usercode;
	private String username;
	private String pwd;
	private String contact;
	private String addr;
	private String email;
	private String remark;
	private Date createtime;
	private String sex;
	private String phone;
	private String movephone;
	private String fax;
	private String lastupdate;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private String vchar4;
	private String vchar5;
	private Set sysRoles = new HashSet(0);

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Userjd getUserjd() {
		return this.userjd;
	}

	public void setUserjd(Userjd userjd) {
		this.userjd = userjd;
	}

	public Useryy getUseryy() {
		return this.useryy;
	}

	public void setUseryy(Useryy useryy) {
		this.useryy = useryy;
	}

	public Usergys getUsergys() {
		return this.usergys;
	}

	public void setUsergys(Usergys usergys) {
		this.usergys = usergys;
	}

	public Dictinfo getDictinfoByGroupid() {
		return this.dictinfoByGroupid;
	}

	public void setDictinfoByGroupid(Dictinfo dictinfoByGroupid) {
		this.dictinfoByGroupid = dictinfoByGroupid;
	}

	public Dictinfo getDictinfoByUserstate() {
		return this.dictinfoByUserstate;
	}

	public void setDictinfoByUserstate(Dictinfo dictinfoByUserstate) {
		this.dictinfoByUserstate = dictinfoByUserstate;
	}

	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMovephone() {
		return this.movephone;
	}

	public void setMovephone(String movephone) {
		this.movephone = movephone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(String lastupdate) {
		this.lastupdate = lastupdate;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	public String getVchar4() {
		return this.vchar4;
	}

	public void setVchar4(String vchar4) {
		this.vchar4 = vchar4;
	}

	public String getVchar5() {
		return this.vchar5;
	}

	public void setVchar5(String vchar5) {
		this.vchar5 = vchar5;
	}

	public Set getSysRoles() {
		return sysRoles;
	}

	public void setSysRoles(Set sysRoles) {
		this.sysRoles = sysRoles;
	}

}
