package com.frotly.yycg.business.system.entity;

// Generated 2015-12-4 21:43:10 by Hibernate Tools 4.0.0

/**
 * Usergysarea generated by hbm2java
 */
public class Usergysarea implements java.io.Serializable {

	private String areaid;
	private SysArea sysArea;
	private Usergys usergys;
	private String vchar1;
	private String vchar2;
	private String vchar3;

	public Usergysarea() {
	}

	public Usergysarea(SysArea sysArea, Usergys usergys) {
		this.sysArea = sysArea;
		this.usergys = usergys;
	}

	public Usergysarea(SysArea sysArea, Usergys usergys, String vchar1,
			String vchar2, String vchar3) {
		this.sysArea = sysArea;
		this.usergys = usergys;
		this.vchar1 = vchar1;
		this.vchar2 = vchar2;
		this.vchar3 = vchar3;
	}

	public String getAreaid() {
		return this.areaid;
	}

	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	public SysArea getSysArea() {
		return this.sysArea;
	}

	public void setSysArea(SysArea sysArea) {
		this.sysArea = sysArea;
	}

	public Usergys getUsergys() {
		return this.usergys;
	}

	public void setUsergys(Usergys usergys) {
		this.usergys = usergys;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

}
