package com.frotly.yycg.business.cgd.entity;

// Generated 2015-12-10 14:17:06 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.frotly.yycg.business.system.entity.Dictinfo;
import com.frotly.yycg.business.system.entity.Usergys;
import com.frotly.yycg.business.system.entity.Useryy;

/**
 * Yycgd generated by hbm2java
 */
public class Yycgd implements java.io.Serializable {

	private Integer id;
	private Dictinfo dictinfoByZt;
	private Useryy useryy;
	private Usergys usergys;
	private String mc;
	private String lxr;
	private String lxdh;
	private String cjr;
	private Date cjtime;
	private Date tjtime;
	private String bz;
	private String shyj;
	private Date shtime;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private String vchar4;
	private String vchar5;
	private Date xgtime;
	private String processinstanceid;
	private Set yycgdmxes = new HashSet(0);


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Dictinfo getDictinfoByZt() {
		return dictinfoByZt;
	}

	public void setDictinfoByZt(Dictinfo dictinfoByZt) {
		this.dictinfoByZt = dictinfoByZt;
	}

	public Useryy getUseryy() {
		return this.useryy;
	}

	public void setUseryy(Useryy useryy) {
		this.useryy = useryy;
	}

	public Usergys getUsergys() {
		return this.usergys;
	}

	public void setUsergys(Usergys usergys) {
		this.usergys = usergys;
	}

	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	public Date getCjtime() {
		return this.cjtime;
	}

	public void setCjtime(Date cjtime) {
		this.cjtime = cjtime;
	}

	public Date getTjtime() {
		return this.tjtime;
	}

	public void setTjtime(Date tjtime) {
		this.tjtime = tjtime;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getShyj() {
		return this.shyj;
	}

	public void setShyj(String shyj) {
		this.shyj = shyj;
	}

	public Date getShtime() {
		return this.shtime;
	}

	public void setShtime(Date shtime) {
		this.shtime = shtime;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	public String getVchar4() {
		return this.vchar4;
	}

	public void setVchar4(String vchar4) {
		this.vchar4 = vchar4;
	}

	public String getVchar5() {
		return this.vchar5;
	}

	public void setVchar5(String vchar5) {
		this.vchar5 = vchar5;
	}

	public Date getXgtime() {
		return this.xgtime;
	}

	public void setXgtime(Date xgtime) {
		this.xgtime = xgtime;
	}

	public String getProcessinstanceid() {
		return this.processinstanceid;
	}

	public void setProcessinstanceid(String processinstanceid) {
		this.processinstanceid = processinstanceid;
	}

	public Set getYycgdmxes() {
		return this.yycgdmxes;
	}

	public void setYycgdmxes(Set yycgdmxes) {
		this.yycgdmxes = yycgdmxes;
	}

}
