package com.frotly.yycg.hessian.server;

// Generated 2015-12-10 12:46:19 by Hibernate Tools 4.0.0

import java.util.Date;

import com.frotly.yycg.business.system.entity.Dictinfo;

/**
 * Ypxx generated by hbm2java
 */
public class Ypxx implements java.io.Serializable {

	private String id;
	private Dictinfo dictinfoByJyzt;
	private Dictinfo dictinfoByLb;
	private String bm;
	private String scqymc;
	private String spmc;
	private Float zbjg;
	private String zpdz;
	private String pzwh;
	private Date pzwhyxq;
	private String jky;
	private String bzcz;
	private String bzdw;
	private Float lsjg;
	private String lsjgcc;
	private String zlcc;
	private String zlccsm;
	private String ypjybg;
	private String ypjybgbm;
	private Date ypjybgyxq;
	private String cpsm;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private String dw;
	private String mc;
	private String jx;
	private String gg;
	private String zhxs;
	private String pinyin;
	private String issheng;

	public Ypxx() {
	}

	public Ypxx(String id, Dictinfo dictinfoByJyzt, String bm, String scqymc,
			String spmc, Float zbjg) {
		this.id = id;
		this.dictinfoByJyzt = dictinfoByJyzt;
		this.bm = bm;
		this.scqymc = scqymc;
		this.spmc = spmc;
		this.zbjg = zbjg;
	}

	public Ypxx(String id, Dictinfo dictinfoByJyzt, Dictinfo dictinfoByLb,
			String bm, String scqymc, String spmc, Float zbjg, String zpdz,
			String pzwh, Date pzwhyxq, String jky, String bzcz, String bzdw,
			Float lsjg, String lsjgcc, String zlcc, String zlccsm,
			String ypjybg, String ypjybgbm, Date ypjybgyxq, String cpsm,
			String vchar1, String vchar2, String vchar3, String dw, String mc,
			String jx, String gg, String zhxs, String pinyin, String issheng) {
		this.id = id;
		this.dictinfoByJyzt = dictinfoByJyzt;
		this.dictinfoByLb = dictinfoByLb;
		this.bm = bm;
		this.scqymc = scqymc;
		this.spmc = spmc;
		this.zbjg = zbjg;
		this.zpdz = zpdz;
		this.pzwh = pzwh;
		this.pzwhyxq = pzwhyxq;
		this.jky = jky;
		this.bzcz = bzcz;
		this.bzdw = bzdw;
		this.lsjg = lsjg;
		this.lsjgcc = lsjgcc;
		this.zlcc = zlcc;
		this.zlccsm = zlccsm;
		this.ypjybg = ypjybg;
		this.ypjybgbm = ypjybgbm;
		this.ypjybgyxq = ypjybgyxq;
		this.cpsm = cpsm;
		this.vchar1 = vchar1;
		this.vchar2 = vchar2;
		this.vchar3 = vchar3;
		this.dw = dw;
		this.mc = mc;
		this.jx = jx;
		this.gg = gg;
		this.zhxs = zhxs;
		this.pinyin = pinyin;
		this.issheng = issheng;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Dictinfo getDictinfoByJyzt() {
		return this.dictinfoByJyzt;
	}

	public void setDictinfoByJyzt(Dictinfo dictinfoByJyzt) {
		this.dictinfoByJyzt = dictinfoByJyzt;
	}

	public Dictinfo getDictinfoByLb() {
		return this.dictinfoByLb;
	}

	public void setDictinfoByLb(Dictinfo dictinfoByLb) {
		this.dictinfoByLb = dictinfoByLb;
	}

	public String getBm() {
		return this.bm;
	}

	public void setBm(String bm) {
		this.bm = bm;
	}

	public String getScqymc() {
		return this.scqymc;
	}

	public void setScqymc(String scqymc) {
		this.scqymc = scqymc;
	}

	public String getSpmc() {
		return this.spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	public Float getZbjg() {
		return this.zbjg;
	}

	public void setZbjg(Float zbjg) {
		this.zbjg = zbjg;
	}

	public String getZpdz() {
		return this.zpdz;
	}

	public void setZpdz(String zpdz) {
		this.zpdz = zpdz;
	}

	public String getPzwh() {
		return this.pzwh;
	}

	public void setPzwh(String pzwh) {
		this.pzwh = pzwh;
	}

	public Date getPzwhyxq() {
		return this.pzwhyxq;
	}

	public void setPzwhyxq(Date pzwhyxq) {
		this.pzwhyxq = pzwhyxq;
	}

	public String getJky() {
		return this.jky;
	}

	public void setJky(String jky) {
		this.jky = jky;
	}

	public String getBzcz() {
		return this.bzcz;
	}

	public void setBzcz(String bzcz) {
		this.bzcz = bzcz;
	}

	public String getBzdw() {
		return this.bzdw;
	}

	public void setBzdw(String bzdw) {
		this.bzdw = bzdw;
	}

	public Float getLsjg() {
		return this.lsjg;
	}

	public void setLsjg(Float lsjg) {
		this.lsjg = lsjg;
	}

	public String getLsjgcc() {
		return this.lsjgcc;
	}

	public void setLsjgcc(String lsjgcc) {
		this.lsjgcc = lsjgcc;
	}

	public String getZlcc() {
		return this.zlcc;
	}

	public void setZlcc(String zlcc) {
		this.zlcc = zlcc;
	}

	public String getZlccsm() {
		return this.zlccsm;
	}

	public void setZlccsm(String zlccsm) {
		this.zlccsm = zlccsm;
	}

	public String getYpjybg() {
		return this.ypjybg;
	}

	public void setYpjybg(String ypjybg) {
		this.ypjybg = ypjybg;
	}

	public String getYpjybgbm() {
		return this.ypjybgbm;
	}

	public void setYpjybgbm(String ypjybgbm) {
		this.ypjybgbm = ypjybgbm;
	}

	public Date getYpjybgyxq() {
		return this.ypjybgyxq;
	}

	public void setYpjybgyxq(Date ypjybgyxq) {
		this.ypjybgyxq = ypjybgyxq;
	}

	public String getCpsm() {
		return this.cpsm;
	}

	public void setCpsm(String cpsm) {
		this.cpsm = cpsm;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	public String getDw() {
		return this.dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}

	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	public String getJx() {
		return this.jx;
	}

	public void setJx(String jx) {
		this.jx = jx;
	}

	public String getGg() {
		return this.gg;
	}

	public void setGg(String gg) {
		this.gg = gg;
	}

	public String getZhxs() {
		return this.zhxs;
	}

	public void setZhxs(String zhxs) {
		this.zhxs = zhxs;
	}

	public String getPinyin() {
		return this.pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	public String getIssheng() {
		return this.issheng;
	}

	public void setIssheng(String issheng) {
		this.issheng = issheng;
	}

}
